set(CMAKE_VERBOSE_MAKEFILE ON)
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_VERSION 1)

# Change to ARMv7
set(CMAKE_SYSTEM_PROCESSOR armv7)
set(CMAKE_LIBRARY_ARCHITECTURE arm-linux-gnueabihf)
set(GCC_VERSION 14.2.0)

set(CMAKE_FIND_ROOT_PATH ${TOOLCHAIN_ROOT})
set(CMAKE_SYSROOT ${TOOLCHAIN_ROOT})

# Update linker flags for ARMv7
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -fPIC \
    -Wl,-rpath-link,${CMAKE_SYSROOT}/${CMAKE_LIBRARY_ARCHITECTURE}/lib \
    -L${CMAKE_SYSROOT}/lib \
    -L${CMAKE_SYSROOT}/${CMAKE_LIBRARY_ARCHITECTURE}\libc\lib \
    -L${CMAKE_SYSROOT}/${CMAKE_LIBRARY_ARCHITECTURE}\libc\usr\lib \
    -L${CMAKE_SYSROOT}/lib/gcc/${CMAKE_LIBRARY_ARCHITECTURE}/${GCC_VERSION}")

# Update compiler flags for ARMv7
set(CMAKE_C_FLAGS "${CMAKE_CXX_FLAGS} -fPIC -march=armv7-a -mfpu=vfp -mfloat-abi=hard -finput-charset=UTF-8 -fexec-charset=UTF-8 -rpath-link,${CMAKE_SYSROOT}/${CMAKE_LIBRARY_ARCHITECTURE}/lib \
    -L${CMAKE_SYSROOT}/${CMAKE_LIBRARY_ARCHITECTURE}\libc\lib \
    -L${CMAKE_SYSROOT}/${CMAKE_LIBRARY_ARCHITECTURE}\libc\usr\lib")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC -march=armv7-a -mfpu=vfp -mfloat-abi=hard -finput-charset=UTF-8 -fexec-charset=UTF-8 -rpath-link,${CMAKE_SYSROOT}/${CMAKE_LIBRARY_ARCHITECTURE}/lib \
    -L${CMAKE_SYSROOT}/${CMAKE_LIBRARY_ARCHITECTURE}\libc\lib \
    -L${CMAKE_SYSROOT}/${CMAKE_LIBRARY_ARCHITECTURE}\libc\usr\lib")

# Compiler Binary
set(BIN_PREFIX ${TOOLCHAIN_ROOT}/bin/${CMAKE_LIBRARY_ARCHITECTURE})

set(CMAKE_C_COMPILER ${BIN_PREFIX}-gcc)
set(CMAKE_CXX_COMPILER ${BIN_PREFIX}-g++)
set(CMAKE_LINKER ${BIN_PREFIX}-ld CACHE STRING "Set the cross-compiler tool LD" FORCE)
set(CMAKE_AR ${BIN_PREFIX}-ar CACHE STRING "Set the cross-compiler tool AR" FORCE)
set(CMAKE_NM ${BIN_PREFIX}-nm CACHE STRING "Set the cross-compiler tool NM" FORCE)
set(CMAKE_OBJCOPY ${BIN_PREFIX}-objcopy CACHE STRING "Set the cross-compiler tool OBJCOPY" FORCE)
set(CMAKE_OBJDUMP ${BIN_PREFIX}-objdump CACHE STRING "Set the cross-compiler tool OBJDUMP" FORCE)
set(CMAKE_RANLIB ${BIN_PREFIX}-ranlib CACHE STRING "Set the cross-compiler tool RANLIB" FORCE)
set(CMAKE_STRIP ${BIN_PREFIX}-strip CACHE STRING "Set the cross-compiler tool STRIP" FORCE)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
