name: build-linux-arm

on:
  push:
    paths-ignore:
      - '**/README.md'
  pull_request:
    paths-ignore:
      - '**/README.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GA_CI_SECRET: ${{ secrets.CI_SECRET }}
  USE_ARTIFACT: true

jobs:
  build-linux-arm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cfg:
        - {target: linuxarmv6l, toolchain_prefix: arm-linux-gnueabihf}
        - {target: linuxarmv7l, toolchain_prefix: arm-linux-gnueabihf}
        - {target: linuxaarch64, toolchain_prefix: aarch64-linux-gnu}

    env:
      TARGET: ${{ matrix.cfg.target }}
      TOOLCHAIN_PREFIX: ${{ matrix.cfg.toolchain_prefix }}

    steps:
    - uses: actions/checkout@v4.1.7
    - name: Setup Environment
      run: |
        echo "SYSROOT=/home/runner/work/apothecary/apothecary/scripts/${{ matrix.cfg.target }}/raspbian" >> $GITHUB_ENV
        echo "TOOLCHAIN_ROOT=/home/runner/work/apothecary/apothecary/scripts/${{ matrix.cfg.target }}/rpi_toolchain" >> $GITHUB_ENV

    - name: Scripts Calc Formula - ${{ matrix.cfg.target }}
      run: ./scripts/calculate_formulas.sh

    - name: Scripts Install
      run: ./scripts/${{ matrix.cfg.target }}/install.sh

    - name: Build - ${{ matrix.cfg.target }}
      run: ./scripts/build.sh

    - name: Package
      run: scripts/package.sh

    - name: Upload binaries as Artifact
      if: github.repository == 'openframeworks/apothecary' && github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/bleeding')
      uses: actions/upload-artifact@v4
      env:
        release: ${{ env.RELEASE }}
      with:
        name: libs-${{ env.TARGET }}-${{ env.ARCH }}-${{ matrix.bundle }}
        path: out/openFrameworksLibs_${{ env.RELEASE }}_${{ env.TARGET }}_${{ matrix.bundle }}.zip
        retention-days: 31
    - name: Update Release arm64
      if: (github.repository == 'openframeworks/apothecary' && github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/bleeding'))
      uses: johnwbyrd/update-release@v1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ env.RELEASE }}
        release: ${{ env.RELEASE }}
        prerelease: ${{ env.PRERELEASE }}
        files: out/openFrameworksLibs_${{ env.RELEASE }}_${{ env.TARGET }}_${{ matrix.bundle }}.zip
