name: build-linux-cross

on:
  push:
    paths: &path-filter
      - '.github/workflows/build-linux-cross.yml'
      - '.github/workflows/detect-path-changes.yml'
      - '.github/path-filters.yml'
      - '.github/actions/**'
      - 'apothecary/apothecary'
      - 'apothecary/ostype.sh'
      - 'apothecary/toolchains/**'
      - 'apothecary/formulas/_depends/**'
      - 'scripts/build.sh'
      - 'scripts/package.sh'
      - 'scripts/package-individual.sh'
      - 'scripts/load.sh'
      - 'scripts/save.sh'
      - 'scripts/secure.sh'
      - 'scripts/downloader.sh'
      - 'scripts/format.sh'
      - 'scripts/calculate_formulas.sh'
      - 'scripts/artifact/**'
      - 'scripts/linux/**'
      - 'apothecary/formulas/glm/**'
      - 'apothecary/formulas/glm.sh'
      - 'apothecary/formulas/json/**'
      - 'apothecary/formulas/json.sh'
      - 'apothecary/formulas/utf8/**'
      - 'apothecary/formulas/utf8.sh'
      - 'apothecary/formulas/brotli/**'
      - 'apothecary/formulas/brotli.sh'
      - 'apothecary/formulas/zlib/**'
      - 'apothecary/formulas/zlib.sh'
      - 'apothecary/formulas/libpng/**'
      - 'apothecary/formulas/libpng.sh'
      - 'apothecary/formulas/glew/**'
      - 'apothecary/formulas/glew.sh'
      - 'apothecary/formulas/glfw/**'
      - 'apothecary/formulas/glfw.sh'
      - 'apothecary/formulas/freetype/**'
      - 'apothecary/formulas/freetype.sh'
      - 'apothecary/formulas/libxml2/**'
      - 'apothecary/formulas/libxml2.sh'
      - 'apothecary/formulas/svgtiny/**'
      - 'apothecary/formulas/svgtiny.sh'
      - 'apothecary/formulas/tess2/**'
      - 'apothecary/formulas/tess2.sh'
      - 'apothecary/formulas/kiss/**'
      - 'apothecary/formulas/kiss.sh'
      - 'apothecary/formulas/FreeImage/**'
      - 'apothecary/formulas/FreeImage.sh'
      - 'apothecary/formulas/fmt/**'
      - 'apothecary/formulas/fmt.sh'
      - 'apothecary/formulas/uriparser/**'
      - 'apothecary/formulas/uriparser.sh'
  pull_request:
    paths: *path-filter

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: write

env:
  TARGET: "linux"
  NO_FORCE: 1
  GA_CI_SECRET: ${{ secrets.CI_SECRET }}
  USE_ARTIFACT: false
  DISABLE_WORKFLOW: "true"

jobs:  
  pre-check:
    runs-on: ubuntu-latest
    outputs:
      workflow_disabled: ${{ steps.check-disabled.outputs.disabled }}
    steps:
    - name: Check if Workflow is disabled
      id: check-disabled
      shell: bash
      run: |
        if [ "${{ env.DISABLE_WORKFLOW }}" == "true" ]; then
          echo "disabled=true" >> $GITHUB_ENV
          echo "::set-output name=disabled::true"
        else
          echo "::set-output name=disabled::false"
        fi
  changes:
    uses: ./.github/workflows/detect-path-changes.yml

  build-linux-aarch64:
    if: |
      needs.pre-check.outputs.workflow_disabled != 'true' &&
      (github.event_name == 'workflow_dispatch' ||
       needs.changes.outputs.engine == 'true' ||
       needs.changes.outputs.linux-scripts == 'true' ||
       needs.changes.outputs.linux-formulas == 'true')
    needs:
      - pre-check
      - changes
    runs-on: ubuntu-latest
    strategy:
        matrix:
          cfg:
          - { distro: ubuntu, target: linux, arch: arm64, gcc: gcc14}
          # - { distro: jetson, target: linux, arch:arm64, gcc: gcc14}
    env:
      TARGET: ${{matrix.cfg.target}}
      GCC: ${{matrix.cfg.gcc}}
      ARCH: ${{matrix.cfg.arch}}
      DISTRO: ${{matrix.cfg.distro}}
    steps:      
    - uses: actions/checkout@v7.0.1
    - name: Check if Workflow is disabled
      run: |
        if [ "${{ env.DISABLE_WORKFLOW }}" == "true" ]; then
          echo "Workflow is disabled. Exiting."
          exit 78
        fi
    - name: Determine Release
      id: vars
      shell: bash
      run: |
        if [[ "${{ github.ref }}" == refs/tags/* ]]; then
          echo "RELEASE=${{ github.ref_name }}" >> $GITHUB_ENV
        elif [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
          echo "RELEASE=nightly" >> $GITHUB_ENV
        elif [[ "${{ github.ref }}" == "refs/heads/bleeding" ]]; then
          echo "RELEASE=latest" >> $GITHUB_ENV
        else
          echo "RELEASE=latest" >> $GITHUB_ENV
        fi
    - name: Scripts Calc Formula - ${{matrix.cfg.target}} - ${{matrix.cfg.gcc}}
      run: ./scripts/calculate_formulas.sh
    - name: Scripts Setup
      run: sudo ./scripts/${{ env.TARGET }}/${{ env.DISTRO }}/${{ env.ARCH }}/setup.sh
    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./scripts/${{ env.TARGET }}/${{ env.DISTRO }}/${{ env.ARCH }}/build.sh
      env:
        BUNDLE: ${{ matrix.bundle }}
    - name: Package
      if: (github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/bleeding'))
      working-directory: ${{ env.GITHUB_WORKSPACE }}
      run: scripts/package.sh
      env:
        BUNDLE: ${{ matrix.bundle }}
    - name: List output directory
      run: ls -lah out/
    - name: Update GitHub Release
      if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/bleeding')
      uses: softprops/action-gh-release@v3.0.2
      with:
        token: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}
        tag_name: ${{ env.RELEASE }}
        draft: false
        files: out/openFrameworksLibs_${{ env.RELEASE }}_${{ env.TARGET }}_${{ env.DISTRO }}_${{ env.ARCH }}_${{ env.GCC }}.tar.bz2
