name: build-vs2022-64

on:
  push:
    paths: &path-filter
      - '.github/workflows/build-vs2022-x64.yml'
      - '.github/workflows/detect-path-changes.yml'
      - '.github/path-filters.yml'
      - '.github/actions/**'
      - 'apothecary/apothecary'
      - 'apothecary/ostype.sh'
      - 'apothecary/toolchains/**'
      - 'apothecary/formulas/_depends/**'
      - 'scripts/build.sh'
      - 'scripts/package.sh'
      - 'scripts/package-individual.sh'
      - 'scripts/load.sh'
      - 'scripts/save.sh'
      - 'scripts/secure.sh'
      - 'scripts/downloader.sh'
      - 'scripts/format.sh'
      - 'scripts/calculate_formulas.sh'
      - 'scripts/artifact/**'
      - 'scripts/vs/**'
      - 'apothecary/formulas/pixman/**'
      - 'apothecary/formulas/pixman.sh'
      - 'apothecary/formulas/zlib/**'
      - 'apothecary/formulas/zlib.sh'
      - 'apothecary/formulas/libpng/**'
      - 'apothecary/formulas/libpng.sh'
      - 'apothecary/formulas/brotli/**'
      - 'apothecary/formulas/brotli.sh'
      - 'apothecary/formulas/freetype/**'
      - 'apothecary/formulas/freetype.sh'
      - 'apothecary/formulas/libxml2/**'
      - 'apothecary/formulas/libxml2.sh'
      - 'apothecary/formulas/svgtiny/**'
      - 'apothecary/formulas/svgtiny.sh'
      - 'apothecary/formulas/assimp/**'
      - 'apothecary/formulas/assimp.sh'
      - 'apothecary/formulas/FreeImage/**'
      - 'apothecary/formulas/FreeImage.sh'
      - 'apothecary/formulas/glew/**'
      - 'apothecary/formulas/glew.sh'
      - 'apothecary/formulas/glfw/**'
      - 'apothecary/formulas/glfw.sh'
      - 'apothecary/formulas/glm/**'
      - 'apothecary/formulas/glm.sh'
      - 'apothecary/formulas/json/**'
      - 'apothecary/formulas/json.sh'
      - 'apothecary/formulas/libusb/**'
      - 'apothecary/formulas/libusb.sh'
      - 'apothecary/formulas/kiss/**'
      - 'apothecary/formulas/kiss.sh'
      - 'apothecary/formulas/portaudio/**'
      - 'apothecary/formulas/portaudio.sh'
      - 'apothecary/formulas/pugixml/**'
      - 'apothecary/formulas/pugixml.sh'
      - 'apothecary/formulas/utf8/**'
      - 'apothecary/formulas/utf8.sh'
      - 'apothecary/formulas/videoInput/**'
      - 'apothecary/formulas/videoInput.sh'
      - 'apothecary/formulas/rtAudio/**'
      - 'apothecary/formulas/rtAudio.sh'
      - 'apothecary/formulas/tess2/**'
      - 'apothecary/formulas/tess2.sh'
      - 'apothecary/formulas/uriparser/**'
      - 'apothecary/formulas/uriparser.sh'
      - 'apothecary/formulas/opencv/**'
      - 'apothecary/formulas/opencv.sh'
      - 'apothecary/formulas/cairo/**'
      - 'apothecary/formulas/cairo.sh'
      - 'apothecary/formulas/fmt/**'
      - 'apothecary/formulas/fmt.sh'
      - 'apothecary/formulas/openssl/**'
      - 'apothecary/formulas/openssl.sh'
      - 'apothecary/formulas/nghttp2/**'
      - 'apothecary/formulas/nghttp2.sh'
      - 'apothecary/formulas/nghttp3/**'
      - 'apothecary/formulas/nghttp3.sh'
      - 'apothecary/formulas/ngtcp2/**'
      - 'apothecary/formulas/ngtcp2.sh'
      - 'apothecary/formulas/libssh2/**'
      - 'apothecary/formulas/libssh2.sh'
      - 'apothecary/formulas/curl/**'
      - 'apothecary/formulas/curl.sh'
      - 'apothecary/formulas/poco/**'
      - 'apothecary/formulas/poco.sh'
      - 'apothecary/formulas/dawn/**'
      - 'apothecary/formulas/dawn.sh'
  pull_request:
    paths: *path-filter

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: write
  actions: read

env:
  TARGET: "vs"
  ARCH: 64
  NO_FORCE: 1
  VS_VER: 17
  GA_CI_SECRET: ${{ secrets.CI_SECRET }}
  USE_ARTIFACT: true
  DISABLE_WORKFLOW: "false"

jobs:  
  pre-check:
    runs-on: ubuntu-latest
    outputs:
      workflow_disabled: ${{ steps.check-disabled.outputs.disabled }}
    steps:
    - name: Check if Workflow is disabled
      id: check-disabled
      shell: bash
      run: |
        if [ "${{ env.DISABLE_WORKFLOW }}" == "true" ]; then
          echo "disabled=true" >> $GITHUB_ENV
          echo "::set-output name=disabled::true"
        else
          echo "::set-output name=disabled::false"
        fi
  changes:
    uses: ./.github/workflows/detect-path-changes.yml

  build-vs2022-64:
    if: |
      needs.pre-check.outputs.workflow_disabled != 'true' &&
      (github.event_name == 'workflow_dispatch' ||
       needs.changes.outputs.engine == 'true' ||
       needs.changes.outputs.vs-scripts == 'true' ||
       (matrix.bundle == 1 && needs.changes.outputs.vs-bundle1 == 'true') ||
       (matrix.bundle == 2 && needs.changes.outputs.vs-bundle2 == 'true'))
    needs:
      - pre-check
      - changes
    runs-on: windows-2022
    strategy:
      matrix:
        bundle: [1,2]
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Check if Workflow is disabled
      shell: bash
      run: |
        if [ "${{ env.DISABLE_WORKFLOW }}" == "true" ]; then
          echo "Workflow is disabled. Exiting."
          exit 78
        fi
    - name: Setup msys2
      uses: msys2/setup-msys2@v2.32.0
      with:
        cache: true
        update: ${{ github.event_name != 'pull_request' }}
        install: >-
          base-devel
          unzip
          dos2unix
          gperf
          git
          python3
          mingw-w64-x86_64-binutils
          mingw-w64-x86_64-clang
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-gcc-libs
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-gdb
          mingw-w64-x86_64-make
          meson
          mingw-w64-x86_64-ninja
    - name: Clone repository
      uses: actions/checkout@v7.0.1
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v3
    - name: Determine Release
      id: vars
      shell: bash
      run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "RELEASE=${{ github.ref_name }}" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/master" ]]; then
            echo "RELEASE=nightly" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/bleeding" ]]; then
            echo "RELEASE=latest" >> $GITHUB_ENV
          else
            echo "RELEASE=latest" >> $GITHUB_ENV
          fi
    - name: Scripts Install
      run: ./scripts/vs/install.sh
    - name: Download named artifact
      if: env.USE_ARTIFACT == 'true'
      uses: ./.github/actions/restore-named-artifact
      with:
        name: libs-${{ env.RELEASE }}-${{ env.TARGET }}-${{ env.ARCH }}-${{ matrix.bundle }}
        workflow-file: build-vs2022-x64.yml
        path: out
    - name: Extract Artifacts to /out
      if: env.USE_ARTIFACT == 'true'
      run: |
          mkdir -p out
          if ls out/*.zip 1> /dev/null 2>&1; then
            for zip in out/*.zip; do
                echo "Extracting $zip..."
                unzip -o "$zip" -d out/
                echo "Removing $zip..."
                rm "$zip"
            done
            echo "First-level extraction and cleanup complete."

            # Check and extract second-level zip files and remove them
            if ls out/*.zip 1> /dev/null 2>&1; then
                for nested_zip in out/*.zip; do
                    echo "Extracting nested zip $nested_zip..."
                    unzip -o "$nested_zip" -d out/
                    echo "Removing $nested_zip..."
                    rm "$nested_zip"
                done
                echo "Second-level extraction and cleanup complete."
            else
                echo "No nested zip files found."
            fi
          else
              echo "No zip files to extract."
          fi
          if ls out/*.tar.bz2 1> /dev/null 2>&1; then
            for tarball in out/*.tar.bz2; do
                echo "Extracting $tarball..."
                tar -xjf "$tarball" -C out/
            done
            echo ".tar.bz2 extraction complete."
            rm -f out/*.tar.bz2
          else
            echo "No .tar.bz2 files to extract."
          fi
          # rm -f xout/*.tar.bz2
          # rm -f out/*.tar.bz2
    - name: List output directory1
      if: env.USE_ARTIFACT == 'true'
      run: ls -lah out/
    - name: Build64
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: scripts/build.sh
      env:
        BUNDLE: ${{ matrix.bundle }}
    - name: Package
      working-directory: ${{ env.GITHUB_WORKSPACE }}
      run: scripts/package.sh
      env:
        BUNDLE: ${{ matrix.bundle }}
        ALWAYS_BUILD: true
    - name: List packaged files
      run: ls -lah out/
    - name: Upload binaries as Artifact
      uses: actions/upload-artifact@v7.0.0
      with:
        name: libs-${{ env.RELEASE }}-${{ env.TARGET }}-${{ env.ARCH }}-${{ matrix.bundle }}
        path: out/openFrameworksLibs_${{ env.RELEASE }}_${{ env.TARGET }}_${{ env.ARCH }}_${{ matrix.bundle }}.zip
        if-no-files-found: error
        retention-days: 90

    - name: Update Release x64
      if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master' || github.ref == 'refs/heads/bleeding')
      uses: softprops/action-gh-release@v3.0.2
      with:
        token: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}
        tag_name: ${{ env.RELEASE }}
        draft: false
        files: out/openFrameworksLibs_${{ env.RELEASE }}_${{ env.TARGET }}_${{ env.ARCH }}_${{ matrix.bundle }}.zip
